### PR TITLE
Setup integration tests

### PR DESCRIPTION
**Pull request by dhruvpeter**
The integration test directory has been set up and a sample integration test is added.
The sample test makes an http call to 'https://www.google.com/' and tests if the status code is 200(OK success status response code)
#15

### CODE REVIEW

**Comment by dhruvpeter** [comment]
Screenshot for a successful build
successful_build

**Comment by dhruvpeter** [comment]
Screenshot of build failure on failure of integration test
build_failure

**Comment by abose** [comment]
@dhruvpeter Thanks for contributing.
Our pull request code analytics does much more deep code checks. We have not yet built ways to run these remote tests locally. 

- [ ] It looks like many of the failures noted are valid. Click on see details and see more details of individual failures. It will have details on how to fix it too.
- [ ] Are we running integration tests as part of the build step? since integration tests take a lot of time, its not usually recommended to run integration tests with `pyb -v` . Can we have another command like `pyb test-integration` for running integ tests?

**Comment by Ushmajit** [comment]
Adding one more point to @abose list. I think we should also add a section in README with clear instructions on how to run integration tests.

**Comment by Ushmajit** [comment]
Integration tests failing in windows due to a known issue in Pybuilder. Tracked here https://github.com/pybuilder/pybuilder/issues/414 . This is fixed in 0.12.0 and actually for Windows integration tests need to inherit environment per:
https://github.com/pybuilder/pybuilder/blob/ff540b75b7feffc51684b2cbc9f76f1eb39ba02/build.py#L156

**Comment by dhruvpeter** [comment]
To skip integration tests during build use the below command
`pyb -x run_integration_tests`

To run only integration tests use the below command
`pyb run_integration_tests -x run_unit_tests`

**Pull request closed without merging**
